-- SCRIPT TO CREATE TABLE first_table IN THE CURRENT DATABASE
-- THE TABLE INCLUDES:
-- id AS INT
-- name AS VARCHAR(256)
-- WILL NOT FAIL IF THE TABLE ALREADY EXISTS

CREATE TABLE IF NOT EXISTS first_table (
	id INT,
	name VARCHAR(256)
);
